# Generated by Django 2.2 on 2019-05-08 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190507_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='icon',
            field=models.ImageField(default='icons/default.png', upload_to='icons/', verbose_name='アイコン'),
        ),
    ]
