# Generated by Django 2.2 on 2019-04-20 21:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='著者名')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13, verbose_name='ISBN')),
                ('title', models.CharField(max_length=200, verbose_name='書籍名')),
                ('published_date', models.DateField(verbose_name='発刊日')),
                ('description', models.TextField(verbose_name='説明')),
                ('image_link', models.URLField(verbose_name='画像URL')),
                ('info_link', models.URLField(verbose_name='書籍情報URL')),
                ('authors', models.ManyToManyField(to='app.Author', verbose_name='著者')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='タグ名')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='スコア')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('reason', models.TextField(verbose_name='読んだ理由')),
                ('body', models.TextField(verbose_name='レビュー')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True, verbose_name='レビュー日時')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Book', verbose_name='対象の本')),
                ('likes', models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='いいねしたユーザ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='レビューユーザ')),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(verbose_name='コメント')),
                ('marked_at', models.DateTimeField(verbose_name='マーク日時')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Book', verbose_name='対象の本')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='マークユーザ')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(verbose_name='コメント')),
                ('commented_at', models.DateTimeField(verbose_name='コメント日時')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Review', verbose_name='対象のレビュー')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='コメントユーザ')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(to='app.Tag', verbose_name='タグ'),
        ),
    ]
