# Generated by Django 2.2 on 2019-05-07 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='コメント'),
        ),
    ]
