# Generated by Django 2.2.1 on 2019-05-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190512_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(error_messages={'unique': 'A book with that ISBN already exists.'}, max_length=13, unique=True, verbose_name='ISBN'),
        ),
    ]
