# Generated by Django 2.2.1 on 2019-05-16 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190515_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(error_messages={'unique': 'この本は既に登録済みです'}, max_length=13, unique=True, verbose_name='ISBN'),
        ),
    ]
