# Generated by Django 2.2.1 on 2019-06-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190516_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commented_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='コメント日時'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='marked_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='マーク日時'),
        ),
    ]
