# Generated by Django 2.2.1 on 2019-06-01 17:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_auto_20190601_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='marks',
            field=models.ManyToManyField(blank=True, related_name='marks', to=settings.AUTH_USER_MODEL, verbose_name='マークしたユーザ'),
        ),
        migrations.DeleteModel(
            name='Mark',
        ),
    ]
